import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { signIn, signOut, useSession } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  const [selectedLevel, setSelectedLevel] = useState(null);
  const { data: session, status } = useSession();

  const handleLevelClick = (level) => {
    if (session) {
      router.push(`/${level}`);
    } else {
      setSelectedLevel(level);
      signIn('google');
    }
  };

  const handleLogin = () => {
    signIn('google');
  };

  const handleLogout = async () => {
    await signOut();
    setSelectedLevel(null);
  };

  useEffect(() => {
    if (status === 'authenticated' && !session) {
      setSelectedLevel(null);
    }
  }, [session, status]);

  useEffect(() => {
    if (selectedLevel && session) {
      router.push(`/${selectedLevel}`);
    }
  }, [selectedLevel, session]);
  const handleParentGuideClick = () => {
    router.push('/guide');
  };


  return (
    <>
      <Head>
        <title>Picture Match</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Autour+One&family=PT+Serif&display=swap" rel="stylesheet" />
      </Head>

      <header className={styles.header}>
        <button className={styles.parentGuideButton} onClick={handleParentGuideClick}>Parent Guide</button>
        {session && (
          <button className={styles.signoutButton} onClick={handleLogout}>
            Sign Out
          </button>
        )}
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 style={{ fontSize: '45px', color:'yellow' }}>Picture Match</h1>
        <div className={styles.myImg}>
          <Image
            className="imag"
            src="/logo.png"
            width={500}
            height={350}
            alt="Picture of the author"
          />
        </div>
        <div className={styles.container}>
          <div
            className={styles.card}
            onClick={() => handleLevelClick('beginer')}
          >
            <div className={styles.logoContainer}>
              <img
                className={styles.logo}
                src="/easy.png"
                alt="Easy Logo"
                width={350}
                height={200}
              />
            </div>
            <h2>Easy Level</h2>
            <p>Train your mind with delightful and simple challenges. Explore a world of fun and unlock your problem-solving skills.</p>
          </div>
          <div
            className={styles.card}
            onClick={() => handleLevelClick('medium')}
          >
            <div className={styles.logoContainer}>
              <img
                className={styles.logo}
                src="medium.png"
                alt="Medium Logo"
                width={350}
                height={200}
              />
            </div>
            <h2>Medium Level</h2>
            <p>Dive deeper into the mind game adventure with thought-provoking puzzles and captivating riddles. Push your mental limits and discover new strategie.</p>
          </div>
          <div
            className={styles.card}
            onClick={() => handleLevelClick('hard')}
          >
            <div className={styles.logoContainer}>
              <img
                className={styles.logo}
                src="hard.png"
                alt="Hard Logo"
                width={350}
                height={180}
              />
            </div>
            <h2>Hard Level</h2>
            <p>Put your mind to the ultimate test with mind-bending enigmas and intricate puzzles. Only the sharpest minds can conquer the challenges that await!.</p>
          </div>
        </div>
      </main>
    </>
  );
}
